// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9C00qx7UYMiINoh1UsCoCUg8rHUJfJ8s',
    appId: '1:1042588907500:web:044922f80ac3457ec032c9',
    messagingSenderId: '1042588907500',
    projectId: 'entrenador-app-863a6',
    authDomain: 'entrenador-app-863a6.firebaseapp.com',
    storageBucket: 'entrenador-app-863a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9U2VYIuwlZNS7i6QQ255mAhbbHbiYrf0',
    appId: '1:1042588907500:android:1f16cf60cfdf7363c032c9',
    messagingSenderId: '1042588907500',
    projectId: 'entrenador-app-863a6',
    storageBucket: 'entrenador-app-863a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCatAa3j42JmbVsP8PUxJEjx_dFY52_yEg',
    appId: '1:1042588907500:ios:f0f2c506ea9369d8c032c9',
    messagingSenderId: '1042588907500',
    projectId: 'entrenador-app-863a6',
    storageBucket: 'entrenador-app-863a6.firebasestorage.app',
    iosBundleId: 'com.example.entrenador',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCatAa3j42JmbVsP8PUxJEjx_dFY52_yEg',
    appId: '1:1042588907500:ios:f0f2c506ea9369d8c032c9',
    messagingSenderId: '1042588907500',
    projectId: 'entrenador-app-863a6',
    storageBucket: 'entrenador-app-863a6.firebasestorage.app',
    iosBundleId: 'com.example.entrenador',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9C00qx7UYMiINoh1UsCoCUg8rHUJfJ8s',
    appId: '1:1042588907500:web:7eb977cfdc4fd928c032c9',
    messagingSenderId: '1042588907500',
    projectId: 'entrenador-app-863a6',
    authDomain: 'entrenador-app-863a6.firebaseapp.com',
    storageBucket: 'entrenador-app-863a6.firebasestorage.app',
  );
}
